apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff-service
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bff-service
  template:
    metadata:
      labels:
        app: bff-service
    spec:
      containers:
        - name: bff-service
          image: aelita1999/bff-service:v1
          ports:
            - containerPort: 8086
          env:
            - name: IDENTITY_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: IDENTITY_SERVICE_URL
            - name: SALARY_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SALARY_SERVICE_URL
            - name: VOTE_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: VOTE_SERVICE_URL
            - name: SEARCH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SEARCH_SERVICE_URL
            - name: STATS_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: STATS_SERVICE_URL
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8086
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8086
            initialDelaySeconds: 60
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: bff-service
  namespace: app
spec:
  selector:
    app: bff-service
  ports:
    - port: 8086
      targetPort: 8086
  type: ClusterIP
