apiVersion: apps/v1
kind: Deployment
metadata:
  name: stats-service
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stats-service
  template:
    metadata:
      labels:
        app: stats-service
    spec:
      containers:
        - name: stats-service
          image: aelita1999/stats-service:v1
          ports:
            - containerPort: 8085
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DB_PASSWORD
          readinessProbe:
            httpGet:
              path: /stats/health
              port: 8085
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /stats/health
              port: 8085
            initialDelaySeconds: 60
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: stats-service
  namespace: app
spec:
  selector:
    app: stats-service
  ports:
    - port: 8085
      targetPort: 8085
  type: ClusterIP
